CREATE TABLE PLAYERS (
    PASSWORD INTEGER CHECK (PASSWORD between 0 AND 281474976710655) PRIMARY KEY,
    NAME TEXT,
    POINTS INTEGER CHECK (POINTS between 0 AND 16383),
    GAMESPLAYED INTEGER CHECK (GAMESPLAYED >= 0),
    FLAGS INTEGER CHECK (FLAGS >= 0)
)

CREATE TABLE CLANS (
    NAME TEXT PRIMARY KEY,
    POINTS INTEGER CHECK (POINTS >= 0)
)

INSERT INTO PLAYERS (PASSWORD, NAME, POINTS, GAMESPLAYED, FLAGS) VALUES (694208745, 'Vkij', 16383, 0, 0)

SELECT NAME, POINTS FROM PLAYERS

SELECT COUNT(*) FROM PLAYERS

UPDATE PLAYERS SET POINTS = 6942 WHERE NAME = 'Vkij'

DELETE FROM PLAYERS WHERE NAME == 'Vkij'

DROP TABLE PLAYERS

ALTER TABLE CLANS RENAME TO PLAYERS
