CREATE TABLE PLAYERS (
    PASSWORD INTEGER CHECK (PASSWORD between 0 AND 281474976710655) PRIMARY KEY,
    USERNAME TEXT,
    ELO INTEGER CHECK (ELO between 0 AND 16383),
    GAMESPLAYED INTEGER CHECK (GAMESPLAYED >= 0),
    IP TEXT
)

INSERT INTO PLAYERS (PASSWORD, USERNAME, ELO, GAMESPLAYED, IP) VALUES (694208745, 'Vkij', 6942, 0, '')

SELECT USERNAME, ELO FROM PLAYERS

DELETE FROM PLAYERS WHERE USERNAME == 'Vkij'

SELECT COUNT(*) FROM PLAYERS

UPDATE PLAYERS SET USERNAME = 'Vkij' WHERE ELO = 16383

CREATE TABLE PLAYERS2 (
    USERNAME TEXT,
    PASSWORD INTEGER CHECK (PASSWORD between 0 AND 281474976710655) PRIMARY KEY,
    ELO INTEGER CHECK (ELO between 0 AND 16383),
    GAMESPLAYED INTEGER CHECK (GAMESPLAYED >= 0),
    IP TEXT
)

INSERT INTO PLAYERS2 (USERNAME, PASSWORD, ELO, GAMESPLAYED, IP) SELECT USERNAME, PASSWORD, ELO, GAMESPLAYED, IP FROM PLAYERS ORDER BY ELO DESC

DROP TABLE PLAYERS

ALTER TABLE PLAYERS2 RENAME TO PLAYERS